# Generated by Django 5.1.4 on 2025-08-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfitserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='queue',
            field=models.CharField(choices=[('nnunet', 'NNUNET'), ('mmap', 'MMAP')], max_length=20),
        ),
    ]
