# Generated by Django 5.1.4 on 2025-07-02 07:40

import bfitserver.models.analysis
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfitserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('queue', models.CharField(choices=[('abd', 'ABD'), ('thigh', 'THIGH'), ('mmap', 'MMAP')], max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('model_params', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfitserver.series')),
            ],
            options={
                'get_latest_by': 'ended_at',
            },
        ),
        migrations.CreateModel(
            name='AnalysisArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact', models.FileField(editable=False, max_length=255, upload_to=bfitserver.models.analysis.analysis_upload_path)),
                ('artifact_type', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_artifact', to='bfitserver.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bfitserver.analysis')),
            ],
            options={
                'get_latest_by': 'modified_at',
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.JSONField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_result', to='bfitserver.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('series', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=20)),
                ('file', models.FileField(blank=True, max_length=255, upload_to=bfitserver.models.analysis.report_upload_path)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bfitserver.study')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmentation_mask', models.FileField(max_length=255, upload_to=bfitserver.models.analysis.analysis_upload_path)),
                ('mask_type', models.TextField()),
                ('is_custom', models.BooleanField(default=False)),
                ('prediction_overrides', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_result', to='bfitserver.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bfitserver.analysis')),
            ],
            options={
                'get_latest_by': 'modified_at',
            },
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.UniqueConstraint(fields=('id', 'owner'), name='analysis_owner_uniq'),
        ),
    ]
