# Generated by Django 5.1.4 on 2025-07-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfitserver', '0002_analysis_analysisartifact_comment_predictionresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
